name: Build VmLoader Driver (No Sign)

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install VS2017 Build Tools (v141)
        run: |
          choco install visualstudio2017-build-tools --no-progress --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.17763"

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build Driver x64 Release
        run: |
          msbuild VmLoader.sln /t:Rebuild /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v141

      - name: Upload compiled sys
        uses: actions/upload-artifact@v4
        with:
          name: VmLoader-x64-Release
          path: bin/x64/Release/vmloader.sys
