name: Build VmLoader Driver (No Sign)

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    # 这个镜像 自带 VS2017 + WDK10，专门编译驱动！
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: 使用 VS2017 + WDK10 环境编译
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          vsversion: 2017

      - name: 编译 x64 Release 驱动
        run: |
          msbuild VmLoader.sln /t:Rebuild /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v141

      - name: 上传编译好的驱动
        uses: actions/upload-artifact@v4
        with:
          name: VmLoader-x64-Release
          path: bin/x64/Release/vmloader.sys
